logging:
  level:
    com:
      jpl: DEBUG

server:
  servlet:
    context-path: /jlp-rest-api
feign:
  client:
    config:
      default:
        loggerLevel: basic
        connectTimeout: 3000
        readTimeout: 3000

app:
  product:
    service:
      name: dressesService
      url: https://api.johnlewis.com/search/api/rest/v2/catalog/products/search/keyword?q=dresses&key=AIzaSyDD_6O5gUgC4tRW5f9kxC0_76XRC8W7_mI